### ISSUE TITLE
Chrome on Windows 10: flickering scrollbar

### ISSUE THREAD

**Issue by shakty** [nodeGame/nodegame-window#7]
Under some circumstances (to be better determined) every updates in the header make the vertical scroll bar appear and disappear. Very annoying! This is happening in current Hawk Dove game BETA. @ewenw

**Comment by shakty** [comment]
It might be due to two methods: W.adjustHeaderOffest and W.adjustFrameHeight:

https://github.com/nodeGame/nodegame-window/blob/master/lib/GameWindow.js#L1932

They are there to make the frame stretch until the end of the page, and they change their style property based on the content of the page. They are called when the frame loads or if the page is resized:

https://github.com/nodeGame/nodegame-window/blob/master/lib/GameWindow.js#L843

They also are invoked when the InfoPanel is opened or closed (the frame must be shifted down):

https://github.com/nodeGame/nodegame-window/blob/master/lib/InfoPanel.js

So it is a complex behavior, it is not an easy fix.

**Comment by shakty** [comment]
Also the hackdove game is a bit strange because it has an horizontal scroll bar also when it is not needed. Could you tell me @ewenw if there is some special settings in the css?

**Comment by ewenw** [comment]
No. I have removed the stylesheet links and the problem still occurs.

**Comment by ewenw** [comment]
This problem exists in the [Prisoner's Dilemma ](https://nodegamedemo.herokuapp.com/prisoner/)implementation as well.

**Comment by shakty** [comment]
Yes, I can reproduce for prisoner. If I stop the visualTimer it stops flickering

**Comment by shakty** [comment]
whatever change you do to the header it adds/remove the scroll bar. 

W.getHeader().innerHTML = "X"; // scroll bar in
W.getHeader().innerHTML = "X"; // scroll bar out
...

It looks like a bug of Chrome to me

**Comment by shakty** [comment]
although it happens only on some games

**Comment by ewenw** [comment]
That's annoying. How come stopGo doesn't suffer from this?

**Comment by shakty** [comment]
https://stackoverflow.com/questions/21563672/google-chrome-vertical-scroll-bars-mysteriously-appear-and-disappear

**Comment by shakty** [comment]
it seems to be an issue for other people also.

**Comment by ewenw** [comment]
A temporary fix would just be to permanently enable scrollbar on Chrome.

**Comment by shakty** [comment]
It seems that removing position: absolute in the CSS rule of ng_mainframe fixes the problem. However, that rule does not affect other games. @ewenw could you see if removing the rule creates problem with other games? Do you think you used some other HTML/CSS that might conflict with that rule?

**Comment by shakty** [comment]
Fixed
